export const CMS_AUTH_TOKEN = 'CMS-AUTH-TOKEN';
export const EXPO_PUSH_TOKEN = 'EXPO-PUSH-TOKEN';

// export const HOST_CMS_API = `http://192.168.0.11:8080/api/CMS`;//집
export const HOST_CMS_API = `http://192.168.22.54:8080/api/CMS`;//pol
// export const HOST_CMS_API = `http://172.30.1.22:8080/api/CMS`;//bil
// export const HOST_CMS_API = `/api/CMS`;


export const LOADER_START = 'LOADER_START'
export const LOADER_END = 'LOADER_END'

export const ALERT_MSG_SHOW = 'ALERT_MSG_SHOW';
export const ALERT_MSG_HIDE = 'ALERT_MSG_HIDE';

export const CONFIRM_MSG_SHOW = 'CONFIRM_MSG_SHOW';
export const CONFIRM_MSG_HIDE = 'CONFIRM_MSG_HIDE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN = 'LOGIN';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT = 'LOGOUT';

export const MODIFY_EMP_PW_REQUEST = 'MODIFY_EMP_PW_REQUEST';
export const MODIFY_EMP_PW = 'MODIFY_EMP_PW'

export const GET_WRK_PLC_LIST_REQUEST = 'GET_WRK_PLC_LIST_REQUEST';
export const GET_WRK_PLC_LIST_SUCCESS = 'GET_WRK_PLC_LIST_SUCCESS';
export const GET_WRK_PLC_LIST_FAILURE = 'GET_WRK_PLC_LIST_FAILURE';

export const APLY_WRK_PLC_REQUEST = 'APLY_WRK_PLC_REQUEST';
export const APLY_WRK_PLC_SUCCESS = 'APLY_WRK_PLC_SUCCESS';
export const APLY_WRK_PLC_FAILURE = 'APLY_WRK_PLC_FAILURE';

export const REG_WRK_PLC_REQUEST = 'REG_WRK_PLC_REQUEST';
export const REG_WRK_PLC_SUCCESS = 'REG_WRK_PLC_SUCCESS';
export const REG_WRK_PLC_FAILURE = 'REG_WRK_PLC_FAILURE';

export const GET_CUR_LOCA_REQUEST = 'GET_CUR_LOCA_REQUEST';
export const GET_CUR_LOCA_SUCCESS = 'GET_CUR_LOCA_SUCCESS';
export const GET_CUR_LOCA_FAILURE = 'GET_CUR_LOCA_FAILURE';

export const GET_EMP_CMT_REQUEST = 'GET_EMP_CMT_REQUEST';
export const GET_EMP_CMT_SUCCESS = 'GET_EMP_CMT_SUCCESS';
export const GET_EMP_CMT_FAILURE = 'GET_EMP_CMT_FAILURE';

export const REG_EMP_CMT_REQUEST = 'REG_EMP_CMT_REQUEST';
export const REG_EMP_CMT_SUCCESS = 'REG_EMP_CMT_SUCCESS';
export const REG_EMP_CMT_FAILURE = 'REG_EMP_CMT_FAILURE';